# Main training for LibriSpeech 100h ASR recipe
defaults:
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  - data: librispeech_100
  - model: branchformer
  - tokenizer: sentencepiece_bpe
  - optimization: default
  - trainer: default
  - logging: tensorboard_wandb
  - callbacks: default
  - _self_

hydra:
  run:
    dir: ${paths.recipe_dir}/outputs/train/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${paths.recipe_dir}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

paths:
  recipe_dir: ${hydra:runtime.cwd}
  exp_dir: ${paths.recipe_dir}/exp/asr_branchformer
  stats_dir: ${paths.recipe_dir}/exp/stats
  tokenizer_dir: ${paths.recipe_dir}/sentencepiece_model

seed: 2024
num_device: 1
vocab_size: 6500

expdir: ${paths.exp_dir}
statsdir: ${paths.stats_dir}

task: asr

runtime:
  train_tokenizer: false
  collect_stats: false
  device: cpu

best_model_criterion:
  - - valid
    - loss
    - min
  - - valid
    - cer
    - min

fit: {}