# Decoding configuration for LibriSpeech 100h
defaults:
  - default.yaml
  - ../dataset.yaml

exp_tag: template


model:
  _target_: espnet2.bin.asr_inference.Speech2Text
  asr_train_config: ${exp_dir}/config.yaml
  asr_model_file: ${exp_dir}/last.ckpt
  beam_size: 1
  ctc_weight: 1.0


metrics:
  - metric:
      _target_: espnet3.asr.metrics.wer.WER
      clean_types: 
    inputs:
      - ref
      - hyp
    apply_to:
      - test-clean
      - test-other

  - metric:
      _target_: espnet3.asr.metrics.cer.CER
      clean_types: 
    inputs:
      - ref
      - hyp
    apply_to:
      - test-clean
      - test-other
