# Optimizer, scheduler, and dataloader defaults

optim:
  _target_: torch.optim.Adam
  lr: 0.002
  weight_decay: 0.000001

scheduler:
  _target_: espnet2.schedulers.warmup_lr.WarmupLR
  warmup_steps: 15000
