dataset:
  test:
    - name: test
      data_src_args:
        split: test
        source_dir: ${dataset_dir}
model:
  _target_: espnet2.bin.asr_inference.Speech2Text
  asr_train_config: ${exp_dir}/config.yaml
  asr_model_file: ${exp_dir}/valid.acc.ave_3best.pth
  beam_size: 20
  ctc_weight: 0.3
input_key: speech
output_fn: egs3.recipe_common.inference.build_output
