
dataset:
  _target_: espnet3.data.DataOrganizer
  test:
    - name: test_1
      dataset:
        _target_: test.espnet3.test_score_runner.DummyDataset
        split: test_1
    - name: test_2
      dataset:
        _target_: test.espnet3.test_score_runner.DummyDataset
        split: test_2

metrics:
  - _target_: test.espnet3.test_score_runner.DummyWER
    inputs:
      - ref
      - hyp
    apply_to: 
      - test_1
      - test_2

  - _target_: test.espnet3.test_score_runner.DummyCER
    inputs:
      - ref
      - hyp
    apply_to: 
      - test_1
      - test_2
