dataset:
  _target_: espnet3.data.DataOrganizer
  test:
    - name: test_unsorted
      dataset:
        _target_: test.espnet3.test_score_runner.DummyDataset

metrics:
  - _target_: test.espnet3.test_score_runner.DummyWER
    inputs:
      - ref
      - hyp
    apply_to:
      - test_unsorted
