dataset:
  _target_: espnet3.data.DataOrganizer
  test:
    - name: test_1
      dataset:
        _target_: test.espnet3.test_score_runner.DummyDataset
        split: test_1

metrics:
  - _target_: test.espnet3.test_score_runner.DummyWER
    inputs: 123
    apply_to:
      - test_1
