dataset:
  _target_: espnet3.data.DataOrganizer
  test:
    - name: test_missing_file
      dataset:
        _target_: test.espnet3.test_score_runner.DummyDataset
        split: test_missing_file

metrics:
  - _target_: test.espnet3.test_score_runner.DummyWER
    inputs:
      - ref
      - hyp
    apply_to:
      - test_missing_file
